import type { Knex } from "knex";

const BIO_ATTRIBUTES = [
  {
    key: "weight_kg",
    normalized_key: "weight",
    label: "Weight",
    unit_type: "weight",
    granularity: "kg",
    measurement_system: "metric",
    min_value_metric: 20,
    max_value_metric: 400,
    min_value_imperial: 44.09,
    max_value_imperial: 881.85,
    is_default: true,
  },
  {
    key: "body_fat_pct",
    normalized_key: "body fat",
    label: "Body fat",
    unit_type: "percentage",
    granularity: "pct",
    measurement_system: "metric",
    min_value_metric: 2,
    max_value_metric: 70,
    min_value_imperial: 2,
    max_value_imperial: 70,
    is_default: true,
  },
  {
    key: "bone_weight_kg",
    normalized_key: "bone weight",
    label: "Bone weight",
    unit_type: "weight",
    granularity: "kg",
    measurement_system: "metric",
    min_value_metric: 1,
    max_value_metric: 10,
    min_value_imperial: 2.2,
    max_value_imperial: 22.05,
    is_default: true,
  },
  {
    key: "body_water_pct",
    normalized_key: "body water",
    label: "Body water",
    unit_type: "percentage",
    granularity: "pct",
    measurement_system: "metric",
    min_value_metric: 30,
    max_value_metric: 80,
    min_value_imperial: 30,
    max_value_imperial: 80,
    is_default: true,
  },
  {
    key: "height_cm",
    normalized_key: "height",
    label: "Height",
    unit_type: "length",
    granularity: "cm",
    measurement_system: "metric",
    min_value_metric: 120,
    max_value_metric: 230,
    min_value_imperial: 47.24,
    max_value_imperial: 90.55,
    is_default: true,
  },
  {
    key: "chest_circumference_cm",
    normalized_key: "chest circumference",
    label: "Chest circumference",
    unit_type: "length",
    granularity: "cm",
    measurement_system: "metric",
    min_value_metric: 50,
    max_value_metric: 160,
    min_value_imperial: 19.69,
    max_value_imperial: 62.99,
    is_default: true,
  },
  {
    key: "waist_circumference_cm",
    normalized_key: "waist circumference",
    label: "Waist circumference",
    unit_type: "length",
    granularity: "cm",
    measurement_system: "metric",
    min_value_metric: 40,
    max_value_metric: 160,
    min_value_imperial: 15.75,
    max_value_imperial: 62.99,
    is_default: true,
  },
  {
    key: "hip_circumference_cm",
    normalized_key: "hip circumference",
    label: "Hip circumference",
    unit_type: "length",
    granularity: "cm",
    measurement_system: "metric",
    min_value_metric: 50,
    max_value_metric: 180,
    min_value_imperial: 19.69,
    max_value_imperial: 70.87,
    is_default: true,
  },
  {
    key: "bicep_circumference_cm",
    normalized_key: "bicep circumference",
    label: "Bicep circumference",
    unit_type: "length",
    granularity: "cm",
    measurement_system: "metric",
    min_value_metric: 15,
    max_value_metric: 80,
    min_value_imperial: 5.91,
    max_value_imperial: 31.5,
    is_default: true,
  },
  {
    key: "thigh_circumference_cm",
    normalized_key: "thigh circumference",
    label: "Thigh circumference",
    unit_type: "length",
    granularity: "cm",
    measurement_system: "metric",
    min_value_metric: 30,
    max_value_metric: 120,
    min_value_imperial: 11.81,
    max_value_imperial: 47.24,
    is_default: true,
  },
  {
    key: "calf_circumference_cm",
    normalized_key: "calf circumference",
    label: "Calf circumference",
    unit_type: "length",
    granularity: "cm",
    measurement_system: "metric",
    min_value_metric: 20,
    max_value_metric: 80,
    min_value_imperial: 7.87,
    max_value_imperial: 31.5,
    is_default: true,
  },
];

const PERF_ATTRIBUTES = [
  {
    key: "vo2_max",
    normalized_key: "vo2 max",
    label: "VO2 Max",
    unit_type: "ratio",
    granularity: "ml/kg/min",
    measurement_system: "metric",
    min_value_metric: 10,
    max_value_metric: 90,
    min_value_imperial: 10,
    max_value_imperial: 90,
    is_default: true,
  },
  {
    key: "ftp_watts",
    normalized_key: "functional threshold power",
    label: "Functional Threshold Power",
    unit_type: "power",
    granularity: "W",
    measurement_system: "metric",
    min_value_metric: 50,
    max_value_metric: 600,
    min_value_imperial: 50,
    max_value_imperial: 600,
    is_default: true,
  },
  {
    key: "run_12min_m",
    normalized_key: "12-minute run",
    label: "12-minute run",
    unit_type: "length",
    granularity: "m",
    measurement_system: "metric",
    min_value_metric: 1000,
    max_value_metric: 4000,
    min_value_imperial: 3280.84,
    max_value_imperial: 13123.36,
    is_default: true,
  },
  {
    key: "dash_100m_sec",
    normalized_key: "100m dash",
    label: "100m dash",
    unit_type: "time",
    granularity: "sec",
    measurement_system: "metric",
    min_value_metric: 9,
    max_value_metric: 30,
    min_value_imperial: 9,
    max_value_imperial: 30,
    is_default: true,
  },
  {
    key: "pushups_1min",
    normalized_key: "max push-ups in a minute",
    label: "Max push-ups in a minute",
    unit_type: "count",
    granularity: "reps",
    measurement_system: "metric",
    min_value_metric: 0,
    max_value_metric: 200,
    min_value_imperial: 0,
    max_value_imperial: 200,
    is_default: true,
  },
  {
    key: "chest_press_1rm_kg",
    normalized_key: "1rm chest press",
    label: "1RM chest press",
    unit_type: "weight",
    granularity: "kg",
    measurement_system: "metric",
    min_value_metric: 5,
    max_value_metric: 300,
    min_value_imperial: 11.02,
    max_value_imperial: 661.39,
    is_default: true,
  },
  {
    key: "squat_1rm_kg",
    normalized_key: "1rm squat",
    label: "1RM squat",
    unit_type: "weight",
    granularity: "kg",
    measurement_system: "metric",
    min_value_metric: 5,
    max_value_metric: 400,
    min_value_imperial: 11.02,
    max_value_imperial: 881.85,
    is_default: true,
  },
  {
    key: "deadlift_1rm_kg",
    normalized_key: "1rm deadlift",
    label: "1RM deadlift",
    unit_type: "weight",
    granularity: "kg",
    measurement_system: "metric",
    min_value_metric: 5,
    max_value_metric: 450,
    min_value_imperial: 11.02,
    max_value_imperial: 992.08,
    is_default: true,
  },
  {
    key: "shoulder_press_1rm_kg",
    normalized_key: "1rm shoulder press",
    label: "1RM shoulder press",
    unit_type: "weight",
    granularity: "kg",
    measurement_system: "metric",
    min_value_metric: 5,
    max_value_metric: 200,
    min_value_imperial: 11.02,
    max_value_imperial: 440.92,
    is_default: true,
  },
  {
    key: "vertical_jump_cm",
    normalized_key: "vertical jump",
    label: "Vertical jump",
    unit_type: "length",
    granularity: "cm",
    measurement_system: "metric",
    min_value_metric: 10,
    max_value_metric: 120,
    min_value_imperial: 3.94,
    max_value_imperial: 47.24,
    is_default: true,
  },
  {
    key: "horizontal_jump_cm",
    normalized_key: "horizontal jump",
    label: "Horizontal jump",
    unit_type: "length",
    granularity: "cm",
    measurement_system: "metric",
    min_value_metric: 50,
    max_value_metric: 400,
    min_value_imperial: 19.69,
    max_value_imperial: 157.48,
    is_default: true,
  },
  {
    key: "sit_and_reach_cm",
    normalized_key: "sit-and-reach distance",
    label: "Sit-and-reach distance",
    unit_type: "length",
    granularity: "cm",
    measurement_system: "metric",
    min_value_metric: -20,
    max_value_metric: 50,
    min_value_imperial: -7.87,
    max_value_imperial: 19.69,
    is_default: true,
  },
];

const ATTRIBUTE_LABELS = [
  ...BIO_ATTRIBUTES.map((row) => ({ key: row.key, label: row.label })),
  ...PERF_ATTRIBUTES.map((row) => ({ key: row.key, label: row.label })),
];

export async function seed(knex: Knex): Promise<void> {
  await knex("bio_attributes").insert(BIO_ATTRIBUTES).onConflict("normalized_key").ignore();
  await knex("perf_attributes").insert(PERF_ATTRIBUTES).onConflict("normalized_key").ignore();

  await knex.raw(
    `
    INSERT INTO translations (namespace, key_path, language, value)
    SELECT x.namespace, x.key_path, x.language, x.value
    FROM jsonb_to_recordset(?::jsonb)
      AS x(namespace text, key_path text, language text, value text)
    ON CONFLICT (namespace, key_path, language) WHERE deleted_at IS NULL
    DO UPDATE SET value = EXCLUDED.value, updated_at = now()
    `,
    [
      JSON.stringify(
        ATTRIBUTE_LABELS.map((row) => ({
          namespace: "user_attributes",
          key_path: `user_attributes.${row.key}`,
          language: "en",
          value: row.label,
        })),
      ),
    ],
  );
}
